FROM op-stack:v1.13.4 AS geth-builder

RUN apt-get update && apt-get install -y --no-install-recommends git

WORKDIR /app/op-geth
# Must build op-stack with migrate feature (in specific branch)
RUN git stash
RUN git checkout feat/cliff/migrate-test
RUN git pull origin feat/cliff/migrate-test
RUN go build -ldflags '-extldflags "-static"' -o build/bin/geth ./cmd/geth

# 2nd stage
FROM op-stack:v1.13.4 AS builder

ARG CHAIN_ID
RUN test -n "${CHAIN_ID}" || (echo "ERROR: CHAIN_ID is not set" && exit 1)
RUN echo "CHAIN_ID: ${CHAIN_ID}"

# Install dependencies (docker CLI, make, etc.)
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        make \
        curl \
        git \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY .env .
COPY config-op/rollup.json /app/op-program/chainconfig/configs/${CHAIN_ID}-rollup.json
COPY config-op/genesis.gz.json /app/op-program/chainconfig/configs/${CHAIN_ID}-genesis-l2.json
# Download deps for building this binary. We will cache this inside image.
RUN echo '🚀 Building reproducible-prestate...' && \
    make reproducible-prestate || echo "⚠️ Make failed during build, check setup"

# Second stage: clean runtime image
FROM op-stack:v1.13.4

# Cache go.mod deps into the image.
COPY --from=builder /go/pkg/mod /go/pkg/mod

RUN apt-get update && \
    apt-get install -y --no-install-recommends docker.io \
    vim && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY --from=geth-builder /app/op-geth/test-pp-op /app/op-geth/test-pp-op
COPY --from=geth-builder /app/op-geth/build/bin/geth /usr/local/bin/geth
COPY --from=builder /app/.env /app/op-geth/test-pp-op/.env
